"""empty message

Revision ID: 26b35266acf0
Revises: 82478b477212
Create Date: 2020-03-11 19:26:34.587579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26b35266acf0'
down_revision = '82478b477212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parameter_results',
    sa.Column('parameter_name', sa.String(length=50), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parameter_name'], ['parameters.parameter_name'], ),
    sa.ForeignKeyConstraint(['result_id'], ['soil_test_results.result_id'], ),
    sa.PrimaryKeyConstraint('parameter_name', 'result_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parameter_results')
    # ### end Alembic commands ###
