"""empty message

Revision ID: 7cbf1b01aac1
Revises: b3681fb72adc
Create Date: 2020-03-11 12:27:25.351314

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7cbf1b01aac1'
down_revision = 'b3681fb72adc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soil_test_devices',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_name')
    )
    op.drop_table('soil_test_device')
    op.drop_index('user_name', table_name='user')
    op.drop_table('user')
    op.alter_column('user_roles', 'role_name',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_roles', 'role_name',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.create_table('user',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('region', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('user_name', 'user', ['user_name'], unique=True)
    op.create_table('soil_test_device',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('users')
    op.drop_table('soil_test_devices')
    # ### end Alembic commands ###
