"""empty message

Revision ID: 82478b477212
Revises: 
Create Date: 2020-03-11 18:17:34.389639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82478b477212'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parameters',
    sa.Column('parameter_name', sa.String(length=50), nullable=False),
    sa.Column('last_updated', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('parameter_name')
    )
    op.create_table('user_permissions',
    sa.Column('permission', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('permission')
    )
    op.create_table('user_roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('role_permissions',
    sa.Column('permission', sa.String(length=200), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission'], ['user_permissions.permission'], ),
    sa.ForeignKeyConstraint(['role_id'], ['user_roles.role_id'], ),
    sa.PrimaryKeyConstraint('permission', 'role_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['user_roles.role_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('soil_test_devices',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('soil_test_results',
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['soil_test_devices.device_id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('soil_test_results')
    op.drop_table('soil_test_devices')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_table('user_roles')
    op.drop_table('user_permissions')
    op.drop_table('parameters')
    # ### end Alembic commands ###
