"""empty message

Revision ID: fafd2c08c54e
Revises: ab433341c9e6
Create Date: 2020-03-12 15:56:01.572014

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fafd2c08c54e'
down_revision = 'ab433341c9e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_permissions',
    sa.Column('permission', sa.String(length=200), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission'], ['user_permissions.permission'], ),
    sa.ForeignKeyConstraint(['role_id'], ['user_roles.role_id'], ),
    sa.PrimaryKeyConstraint('permission', 'role_id')
    )
    op.drop_table('user_role_permissions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_role_permissions',
    sa.Column('permission', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission'], ['user_permissions.permission'], name='user_role_permissions_ibfk_1'),
    sa.ForeignKeyConstraint(['role_id'], ['user_roles.role_id'], name='user_role_permissions_ibfk_2'),
    sa.PrimaryKeyConstraint('permission', 'role_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('role_permissions')
    # ### end Alembic commands ###
